# Generated by Django 5.0 on 2023-12-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_rename_location_organization_head_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='parent_organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.organization'),
        ),
    ]
